# Generated by Django 2.2.6 on 2019-10-06 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='authotr',
            new_name='author',
        ),
    ]
